project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd

format:
  html:
    comments:
      giscus: 
        repo: nicolas-tm/pub_test_quarto
  docx: default
  jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: true

